#ifndef HAIREVENT_CONFIG_H
#define HAIREVENT_CONFIG_H
#define HE_CFG_ENABLED                   1
#define HE_CFG_ENABLE_ACTIVE_OBJECT      1
#define HE_CFG_ENABLE_FLAT_STATE_MACHINE 1
#define HE_CFG_ENABLE_HIERARCHICAL_SM    0
#define HE_CFG_ENABLE_TIME_EVENT         1
#define HE_CFG_ENABLE_EVENT_POOL         1
#define HE_CFG_ENABLE_PUBLISH_SUBSCRIBE  0
#define HE_CFG_MAX_ACTIVE_OBJECTS        8U
#endif
