include("${CMAKE_CURRENT_LIST_DIR}/hairtos_examples.cmake")

if(NOT DEFINED HAIRTOS_EXAMPLE)
    set(HAIRTOS_EXAMPLE "${HAIRTOS_DEFAULT_EXAMPLE}")
endif()
if(NOT DEFINED HAIRTOS_ENVIRONMENT)
    set(HAIRTOS_ENVIRONMENT auto)
endif()

if(HAIRTOS_ENVIRONMENT STREQUAL "auto")
    list(FIND HAIRTOS_HOST_ONLY_EXAMPLES "${HAIRTOS_EXAMPLE}" host_only_index)
    if(host_only_index EQUAL -1)
        set(resolved target)
    else()
        set(resolved host)
    endif()
elseif(HAIRTOS_ENVIRONMENT STREQUAL "host" OR HAIRTOS_ENVIRONMENT STREQUAL "target")
    set(resolved "${HAIRTOS_ENVIRONMENT}")
else()
    message(FATAL_ERROR "HAIRTOS_ENVIRONMENT must be auto, host, or target")
endif()

hairtos_validate_example("${resolved}" "${HAIRTOS_EXAMPLE}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E echo "${resolved}")
