#ifndef HR_STATUS_H
#define HR_STATUS_H
typedef enum { HR_OK=0, HR_ERROR_INVALID_ARGUMENT, HR_ERROR_INVALID_STATE,
HR_ERROR_TIMEOUT, HR_ERROR_QUEUE_FULL, HR_ERROR_QUEUE_EMPTY, HR_ERROR_NO_MEMORY,
HR_ERROR_NOT_OWNER, HR_ERROR_FROM_ISR, HR_ERROR_NOT_SUPPORTED, HR_ERROR_INTERNAL } hr_status_t;
#endif
